-- ============================================================================
-- 01 · Esquema completo en PostgreSQL
-- ============================================================================
--
-- El estado final del esquema que en MariaDB construian 55 migraciones y los
-- guiones de `database/sql/multi-tenant/` (archivados en
-- `database/historico-mariadb/`). Tablas, columnas, claves, unicos, indices,
-- CHECK, columnas generadas y el trigger de cupo, con los MISMOS nombres: el
-- codigo reconoce algunos errores por el nombre del indice que salto
-- (`App\Support\ErrorDeBaseDeDatos`).
--
-- Idempotente: se puede correr dos veces seguidas, o de nuevo tras un fallo a
-- medias, y termina en el mismo estado. Todo es `IF NOT EXISTS` o `OR
-- REPLACE`. PostgreSQL 18 o superior (ver el cotejo). Con el cliente:
--   psql -h ... -p ... -U ... -d nombre_de_la_base -f este_archivo.sql
--
-- Las traducciones que no son evidentes:
--
-- * COTEJO. MariaDB comparaba con `utf8mb4_unicode_ci`, que no distingue
--   mayusculas NI tildes: `Ana` entra como `ana`, el buscador encuentra
--   «musica» en «Música» y un departamento «musica» choca con «Música». En
--   PostgreSQL eso es el cotejo ICU no determinista `insensible`, puesto en
--   cada columna de texto. Hace falta la 18: es la primera que admite LIKE con
--   un cotejo no determinista. Lo que NO replica: MariaDB ignoraba los
--   espacios al final al comparar (`'a' = 'a '`); aqui no.
--   Las expresiones regulares no admiten este cotejo, por eso el CHECK del
--   color va con `COLLATE "C"`.
--
-- * SIN SIGNO. PostgreSQL no tiene enteros sin signo. Las claves pasan a
--   `bigint` (nunca son negativas); las columnas de datos pasan al entero
--   siguiente con un CHECK que conserva el rango de antes, salvo donde ya
--   habia uno mas estrecho.
--
-- * BOOLEANOS. `tinyint(1)` pasa a `boolean`.
--
-- * COLUMNAS GENERADAS. MariaDB las tenia VIRTUAL; aqui son STORED (la
--   unica forma que admite un indice unico). Mismo nombre, misma regla.
--
-- * `restablecimientos_clave.created_at` llevaba `ON UPDATE
--   CURRENT_TIMESTAMP`, que PostgreSQL no tiene: lo hace un trigger.
--
-- * FECHAS. `datetime` y `timestamp` pasan a `timestamp(0)` sin zona: la
--   aplicacion guarda la hora local y asi la lee.
-- ============================================================================

CREATE COLLATION IF NOT EXISTS insensible (
  provider = icu, locale = 'und-u-ks-level1', deterministic = false
);

-- ----------------------------------------------------------------------------
-- Instituciones
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS instituciones (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(80) COLLATE insensible NOT NULL,
  subdominio  varchar(63) COLLATE insensible NULL,
  estado      varchar(20) COLLATE insensible NOT NULL DEFAULT 'activa',
  fecha_alta  timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
  CONSTRAINT instituciones_subdominio_unique UNIQUE (subdominio),
  CONSTRAINT nombre_de_institucion_no_vacio CHECK (nombre <> ''),
  CONSTRAINT estado_de_institucion_valido CHECK (estado IN ('activa', 'suspendida'))
);

-- La 1 existe SIEMPRE, tambien en una base recien creada: es la institucion
-- por defecto. `php artisan instalar` le pone el nombre de verdad.
INSERT INTO instituciones (id, nombre, estado)
VALUES (1, 'Institución', 'activa')
ON CONFLICT (id) DO NOTHING;

-- Con la 1 puesta a mano, la secuencia tiene que saltarla.
SELECT setval(pg_get_serial_sequence('instituciones', 'id'), (SELECT MAX(id) FROM instituciones));

-- ----------------------------------------------------------------------------
-- Cuentas y personas
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id     bigint NOT NULL,
  username           varchar(150) COLLATE insensible NOT NULL,
  email              varchar(255) COLLATE insensible NULL,
  email_verified_at  timestamp(0) NULL,
  password           varchar(255) COLLATE insensible NOT NULL,
  activo             boolean NOT NULL DEFAULT true,
  remember_token     varchar(100) COLLATE insensible NULL,
  created_at         timestamp(0) NULL,
  updated_at         timestamp(0) NULL,
  CONSTRAINT users_username_unique UNIQUE (username),
  CONSTRAINT fk_users_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id)
);
CREATE INDEX IF NOT EXISTS fk_users_institucion ON users (institucion_id);

CREATE TABLE IF NOT EXISTS perfiles (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id    bigint NOT NULL,
  user_id           bigint NOT NULL,
  rol               varchar(25) COLLATE insensible NOT NULL DEFAULT '',
  nombre_completo   varchar(90) COLLATE insensible NOT NULL,
  fecha_nacimiento  date NULL,
  telefono          varchar(15) COLLATE insensible NULL,
  foto_perfil       varchar(255) COLLATE insensible NOT NULL DEFAULT '',
  codigo_qr         char(16) COLLATE insensible NULL,
  suprimido_en      timestamp(0) NULL,
  created_at        timestamp(0) NULL,
  updated_at        timestamp(0) NULL,
  CONSTRAINT perfiles_user_id_unique UNIQUE (user_id),
  CONSTRAINT perfiles_codigo_qr_unique UNIQUE (codigo_qr),
  CONSTRAINT fk_perfiles_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT perfiles_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT rol_valido CHECK (rol IN ('administrador', 'director', 'profesor', 'estudiante', 'institucion_externa', ''))
);
CREATE INDEX IF NOT EXISTS perfiles_rol_index ON perfiles (rol);
CREATE INDEX IF NOT EXISTS perfiles_nombre_completo_index ON perfiles (nombre_completo);
CREATE INDEX IF NOT EXISTS perfiles_institucion_rol ON perfiles (institucion_id, rol);
CREATE INDEX IF NOT EXISTS perfiles_institucion_nombre ON perfiles (institucion_id, nombre_completo);

CREATE TABLE IF NOT EXISTS restablecimientos_clave (
  user_id         bigint NOT NULL PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  token           char(64) COLLATE insensible NOT NULL,
  created_at      timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
  CONSTRAINT restablecimientos_clave_token_unique UNIQUE (token),
  CONSTRAINT fk_restablecimientos_clave_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT restablecimientos_clave_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS fk_restablecimientos_clave_institucion ON restablecimientos_clave (institucion_id);

-- El `ON UPDATE CURRENT_TIMESTAMP` de MariaDB: si la fila cambia y nadie toca
-- `created_at`, se pone la hora de ahora. Si la escritura la pone a mano, se
-- respeta, igual que alli.
CREATE OR REPLACE FUNCTION restablecimiento_al_dia() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.created_at IS NOT DISTINCT FROM OLD.created_at
     AND (NEW.user_id, NEW.institucion_id, NEW.token)
         IS DISTINCT FROM (OLD.user_id, OLD.institucion_id, OLD.token) THEN
    NEW.created_at := LOCALTIMESTAMP(0);
  END IF;
  RETURN NEW;
END
$$;

CREATE OR REPLACE TRIGGER restablecimiento_al_dia
  BEFORE UPDATE ON restablecimientos_clave
  FOR EACH ROW EXECUTE FUNCTION restablecimiento_al_dia();

-- ----------------------------------------------------------------------------
-- Configuracion, departamentos y periodos
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS configuracion_institucion (
  id                                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id                         bigint NOT NULL,
  nombre_institucion                     varchar(80) COLLATE insensible NOT NULL DEFAULT 'Casa de la Cultura',
  entidad_nit                            varchar(40) COLLATE insensible NOT NULL DEFAULT '',
  entidad_direccion                      varchar(160) COLLATE insensible NOT NULL DEFAULT '',
  entidad_correo                         varchar(120) COLLATE insensible NOT NULL DEFAULT '',
  entidad_telefono                       varchar(40) COLLATE insensible NOT NULL DEFAULT '',
  politica_datos                         text COLLATE insensible NULL,
  finalidad_datos                        varchar(255) COLLATE insensible NOT NULL DEFAULT '',
  finalidad_imagen                       varchar(255) COLLATE insensible NOT NULL DEFAULT '',
  consentimiento_mayor                   varchar(255) COLLATE insensible NOT NULL DEFAULT '',
  consentimiento_menor                   varchar(255) COLLATE insensible NOT NULL DEFAULT '',
  correo_servidor                        varchar(160) COLLATE insensible NOT NULL DEFAULT '',
  correo_puerto                          integer NOT NULL DEFAULT 465,
  correo_cifrado                         varchar(10) COLLATE insensible NOT NULL DEFAULT 'smtps',
  correo_usuario                         varchar(160) COLLATE insensible NOT NULL DEFAULT '',
  correo_clave                           text COLLATE insensible NULL,
  logo                                   varchar(255) COLLATE insensible NOT NULL DEFAULT '',
  firma                                  varchar(255) COLLATE insensible NOT NULL DEFAULT '',
  firmante_nombre                        varchar(120) COLLATE insensible NOT NULL DEFAULT '',
  firmante_cargo                         varchar(80) COLLATE insensible NOT NULL DEFAULT '',
  color_acento                           char(7) COLLATE insensible NOT NULL DEFAULT '#0a7a59',
  limite_promotorias_por_periodo         smallint NOT NULL DEFAULT 2,
  promotorias_visibles_para_estudiantes  boolean NOT NULL DEFAULT true,
  created_at                             timestamp(0) NULL,
  updated_at                             timestamp(0) NULL,
  alerta_clase_no_dictada                boolean NOT NULL DEFAULT true,
  alerta_abandono                        boolean NOT NULL DEFAULT true,
  faltas_para_abandono                   smallint NOT NULL DEFAULT 5,
  alertas_desde                          date NULL,
  recordar_encuesta                      boolean NOT NULL DEFAULT true,
  correo_obligatorio                     boolean NOT NULL DEFAULT false,
  CONSTRAINT una_configuracion_por_institucion UNIQUE (institucion_id),
  CONSTRAINT fk_configuracion_institucion_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT limite_promotorias_valido CHECK (limite_promotorias_por_periodo BETWEEN 1 AND 6),
  CONSTRAINT color_acento_hex CHECK (color_acento COLLATE "C" ~ '^#[0-9a-fA-F]{6}$'),
  CONSTRAINT correo_puerto_en_rango CHECK (correo_puerto BETWEEN 0 AND 65535),
  CONSTRAINT faltas_para_abandono_en_rango CHECK (faltas_para_abandono BETWEEN 0 AND 255)
);

CREATE TABLE IF NOT EXISTS areas (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  nombre          varchar(60) COLLATE insensible NOT NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT areas_nombre_por_institucion UNIQUE (institucion_id, nombre),
  CONSTRAINT fk_areas_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id)
);

CREATE TABLE IF NOT EXISTS areas_dirigidas (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  perfil_id       bigint NOT NULL,
  area_id         bigint NOT NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT un_area_una_vez_por_director UNIQUE (perfil_id, area_id),
  CONSTRAINT areas_dirigidas_area_id_foreign FOREIGN KEY (area_id) REFERENCES areas (id) ON DELETE CASCADE,
  CONSTRAINT areas_dirigidas_perfil_id_foreign FOREIGN KEY (perfil_id) REFERENCES perfiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_areas_dirigidas_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id)
);
CREATE INDEX IF NOT EXISTS areas_dirigidas_area_id_index ON areas_dirigidas (area_id);
CREATE INDEX IF NOT EXISTS fk_areas_dirigidas_institucion ON areas_dirigidas (institucion_id);

CREATE TABLE IF NOT EXISTS periodos (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id       bigint NOT NULL,
  nombre               varchar(20) COLLATE insensible NOT NULL,
  fecha_inicio         date NOT NULL,
  fecha_fin            date NOT NULL,
  activo               boolean NOT NULL DEFAULT false,
  matriculas_abiertas  boolean NOT NULL DEFAULT false,
  created_at           timestamp(0) NULL,
  updated_at           timestamp(0) NULL,
  -- Emula un indice unico PARCIAL: 1 en el periodo en curso, NULL en los
  -- demas, y los NULL no chocan. Un periodo en curso por institucion.
  activo_marca         smallint GENERATED ALWAYS AS (CASE WHEN activo THEN 1 END) STORED,
  CONSTRAINT periodos_nombre_por_institucion UNIQUE (institucion_id, nombre),
  CONSTRAINT un_periodo_activo_por_institucion UNIQUE (institucion_id, activo_marca),
  CONSTRAINT fk_periodos_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id)
);

-- ----------------------------------------------------------------------------
-- Estudiantes: acudiente, ficha, documentos, encuesta demografica
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS acudientes (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id              bigint NOT NULL,
  nombre                      varchar(90) COLLATE insensible NOT NULL,
  telefono                    varchar(15) COLLATE insensible NOT NULL,
  autoriza_tratamiento_datos  boolean NOT NULL DEFAULT false,
  fecha_autorizacion          timestamp(0) NULL,
  created_at                  timestamp(0) NULL,
  updated_at                  timestamp(0) NULL,
  CONSTRAINT fk_acudientes_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id)
);
CREATE INDEX IF NOT EXISTS fk_acudientes_institucion ON acudientes (institucion_id);

CREATE TABLE IF NOT EXISTS datos_estudiante (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id       bigint NOT NULL,
  perfil_id            bigint NOT NULL,
  documento_identidad  varchar(15) COLLATE insensible NOT NULL,
  acudiente_id         bigint NULL,
  created_at           timestamp(0) NULL,
  updated_at           timestamp(0) NULL,
  CONSTRAINT datos_estudiante_perfil_id_unique UNIQUE (perfil_id),
  CONSTRAINT un_documento_de_identidad_por_institucion UNIQUE (institucion_id, documento_identidad),
  CONSTRAINT datos_estudiante_acudiente_id_foreign FOREIGN KEY (acudiente_id) REFERENCES acudientes (id) ON DELETE SET NULL,
  CONSTRAINT datos_estudiante_perfil_id_foreign FOREIGN KEY (perfil_id) REFERENCES perfiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_datos_estudiante_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id)
);
CREATE INDEX IF NOT EXISTS datos_estudiante_acudiente_id_foreign ON datos_estudiante (acudiente_id);

CREATE TABLE IF NOT EXISTS documentos_requeridos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  nombre          varchar(60) COLLATE insensible NOT NULL,
  descripcion     varchar(200) COLLATE insensible NOT NULL DEFAULT '',
  plantilla       varchar(30) COLLATE insensible NOT NULL DEFAULT '',
  obligatorio     boolean NOT NULL DEFAULT true,
  activo          boolean NOT NULL DEFAULT true,
  orden           integer NOT NULL DEFAULT 0,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT un_documento_por_nombre_e_institucion UNIQUE (institucion_id, nombre),
  CONSTRAINT fk_documentos_requeridos_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT orden_en_rango CHECK (orden BETWEEN 0 AND 65535)
);
CREATE INDEX IF NOT EXISTS documentos_requeridos_orden_nombre_index ON documentos_requeridos (orden, nombre);
CREATE INDEX IF NOT EXISTS documentos_requeridos_institucion_orden ON documentos_requeridos (institucion_id, orden, nombre);

CREATE TABLE IF NOT EXISTS documentos_estudiante (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id       bigint NOT NULL,
  datos_estudiante_id  bigint NOT NULL,
  requerido_id         bigint NOT NULL,
  archivo              varchar(255) COLLATE insensible NOT NULL,
  subido               timestamp(0) NOT NULL,
  created_at           timestamp(0) NULL,
  updated_at           timestamp(0) NULL,
  CONSTRAINT un_archivo_por_documento_y_estudiante UNIQUE (datos_estudiante_id, requerido_id),
  CONSTRAINT documentos_estudiante_datos_estudiante_id_foreign FOREIGN KEY (datos_estudiante_id) REFERENCES datos_estudiante (id) ON DELETE CASCADE,
  CONSTRAINT documentos_estudiante_requerido_id_foreign FOREIGN KEY (requerido_id) REFERENCES documentos_requeridos (id) ON DELETE CASCADE,
  CONSTRAINT fk_documentos_estudiante_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id)
);
CREATE INDEX IF NOT EXISTS documentos_estudiante_requerido_id_foreign ON documentos_estudiante (requerido_id);
CREATE INDEX IF NOT EXISTS fk_documentos_estudiante_institucion ON documentos_estudiante (institucion_id);

CREATE TABLE IF NOT EXISTS encuestas_demograficas (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id              bigint NOT NULL,
  perfil_id                   bigint NOT NULL,
  genero                      varchar(2) COLLATE insensible NOT NULL,
  barrio                      varchar(60) COLLATE insensible NOT NULL,
  estrato                     smallint NOT NULL,
  nivel_educativo             varchar(20) COLLATE insensible NOT NULL,
  ocupacion                   varchar(20) COLLATE insensible NOT NULL,
  zona                        varchar(20) COLLATE insensible NOT NULL DEFAULT '',
  afiliacion_salud            varchar(20) COLLATE insensible NOT NULL DEFAULT '',
  grupo_etnico                varchar(20) COLLATE insensible NOT NULL DEFAULT '',
  discapacidad                varchar(20) COLLATE insensible NOT NULL DEFAULT '',
  victima_conflicto_armado    varchar(20) COLLATE insensible NOT NULL DEFAULT '',
  autoriza_tratamiento_datos  boolean NOT NULL DEFAULT false,
  fecha_autorizacion          timestamp(0) NULL,
  created_at                  timestamp(0) NULL,
  updated_at                  timestamp(0) NULL,
  CONSTRAINT encuestas_demograficas_perfil_id_unique UNIQUE (perfil_id),
  CONSTRAINT encuestas_demograficas_perfil_id_foreign FOREIGN KEY (perfil_id) REFERENCES perfiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_encuestas_demograficas_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT estrato_valido CHECK (estrato BETWEEN 1 AND 6)
);
CREATE INDEX IF NOT EXISTS fk_encuestas_demograficas_institucion ON encuestas_demograficas (institucion_id);

-- ----------------------------------------------------------------------------
-- Promotorias, grupos y matriculas
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS promotorias (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  nombre          varchar(60) COLLATE insensible NOT NULL,
  area_id         bigint NOT NULL,
  profesor_id     bigint NULL,
  enlace_token    char(16) COLLATE insensible NULL,
  enlace_abierto  boolean NOT NULL DEFAULT false,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT promotorias_enlace_token_unique UNIQUE (enlace_token),
  CONSTRAINT fk_promotorias_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT promotorias_area_id_foreign FOREIGN KEY (area_id) REFERENCES areas (id),
  CONSTRAINT promotorias_profesor_id_foreign FOREIGN KEY (profesor_id) REFERENCES perfiles (id)
);
CREATE INDEX IF NOT EXISTS promotorias_area_id_foreign ON promotorias (area_id);
CREATE INDEX IF NOT EXISTS promotorias_profesor_id_foreign ON promotorias (profesor_id);
CREATE INDEX IF NOT EXISTS promotorias_nombre_index ON promotorias (nombre);
CREATE INDEX IF NOT EXISTS promotorias_institucion_nombre ON promotorias (institucion_id, nombre);

CREATE TABLE IF NOT EXISTS encuestas_satisfaccion (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id         bigint NOT NULL,
  perfil_id              bigint NOT NULL,
  promotoria_id          bigint NULL,
  periodo_id             bigint NOT NULL,
  satisfaccion_general   smallint NOT NULL,
  calificacion_profesor  smallint NOT NULL,
  horario_funciono       boolean NOT NULL,
  recomendaria           boolean NOT NULL,
  comentario             text COLLATE insensible NULL,
  fecha                  timestamp(0) NOT NULL,
  created_at             timestamp(0) NULL,
  updated_at             timestamp(0) NULL,
  CONSTRAINT una_encuesta_por_promotoria_y_periodo UNIQUE (perfil_id, periodo_id, promotoria_id),
  CONSTRAINT encuestas_satisfaccion_perfil_id_foreign FOREIGN KEY (perfil_id) REFERENCES perfiles (id) ON DELETE CASCADE,
  CONSTRAINT encuestas_satisfaccion_periodo_id_foreign FOREIGN KEY (periodo_id) REFERENCES periodos (id),
  CONSTRAINT encuestas_satisfaccion_promotoria_id_foreign FOREIGN KEY (promotoria_id) REFERENCES promotorias (id),
  CONSTRAINT fk_encuestas_satisfaccion_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT escalas_validas CHECK (satisfaccion_general BETWEEN 1 AND 5 AND calificacion_profesor BETWEEN 1 AND 5)
);
CREATE INDEX IF NOT EXISTS encuestas_satisfaccion_periodo_id_foreign ON encuestas_satisfaccion (periodo_id);
CREATE INDEX IF NOT EXISTS encuestas_satisfaccion_promotoria_id_foreign ON encuestas_satisfaccion (promotoria_id);
CREATE INDEX IF NOT EXISTS encuestas_satisfaccion_institucion_periodo ON encuestas_satisfaccion (institucion_id, periodo_id);

CREATE TABLE IF NOT EXISTS cupos_promotoria (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  promotoria_id   bigint NOT NULL,
  periodo_id      bigint NOT NULL,
  cupo_maximo     bigint NOT NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT un_cupo_por_promotoria_y_periodo UNIQUE (promotoria_id, periodo_id),
  CONSTRAINT cupos_promotoria_periodo_id_foreign FOREIGN KEY (periodo_id) REFERENCES periodos (id) ON DELETE CASCADE,
  CONSTRAINT cupos_promotoria_promotoria_id_foreign FOREIGN KEY (promotoria_id) REFERENCES promotorias (id) ON DELETE CASCADE,
  CONSTRAINT fk_cupos_promotoria_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT cupo_maximo_en_rango CHECK (cupo_maximo BETWEEN 0 AND 4294967295)
);
CREATE INDEX IF NOT EXISTS cupos_promotoria_periodo_id_foreign ON cupos_promotoria (periodo_id);
CREATE INDEX IF NOT EXISTS fk_cupos_promotoria_institucion ON cupos_promotoria (institucion_id);

CREATE TABLE IF NOT EXISTS grupos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  promotoria_id   bigint NOT NULL,
  nombre          varchar(60) COLLATE insensible NOT NULL,
  nivel           varchar(12) COLLATE insensible NOT NULL,
  salon           varchar(40) COLLATE insensible NOT NULL,
  cupo_maximo     bigint NOT NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT un_nombre_por_promotoria UNIQUE (promotoria_id, nombre),
  CONSTRAINT fk_grupos_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT grupos_promotoria_id_foreign FOREIGN KEY (promotoria_id) REFERENCES promotorias (id) ON DELETE CASCADE,
  CONSTRAINT nivel_valido CHECK (nivel IN ('basico', 'intermedio', 'avanzado')),
  CONSTRAINT nombre_no_vacio CHECK (nombre <> ''),
  CONSTRAINT cupo_maximo_en_rango CHECK (cupo_maximo BETWEEN 0 AND 4294967295)
);
CREATE INDEX IF NOT EXISTS grupos_institucion_nombre ON grupos (institucion_id, nombre);

CREATE TABLE IF NOT EXISTS matriculas (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  estudiante_id   bigint NOT NULL,
  promotoria_id   bigint NOT NULL,
  periodo_id      bigint NOT NULL,
  fecha           timestamp(0) NOT NULL,
  estado          varchar(24) COLLATE insensible NOT NULL DEFAULT 'pendiente',
  motivo_retiro   varchar(20) COLLATE insensible NULL,
  ranura          smallint NOT NULL DEFAULT 1,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  -- La ranura que OCUPA: la de siempre mientras no este retirada, NULL
  -- despues. Una cancelacion pedida y sin resolver sigue ocupandola.
  ranura_activa   smallint GENERATED ALWAYS AS (CASE WHEN estado <> 'retirada' THEN ranura END) STORED,
  CONSTRAINT unica_matricula_por_periodo UNIQUE (estudiante_id, promotoria_id, periodo_id),
  CONSTRAINT una_matricula_por_ranura_y_periodo UNIQUE (estudiante_id, periodo_id, ranura_activa),
  CONSTRAINT fk_matriculas_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT matriculas_estudiante_id_foreign FOREIGN KEY (estudiante_id) REFERENCES perfiles (id) ON DELETE CASCADE,
  CONSTRAINT matriculas_periodo_id_foreign FOREIGN KEY (periodo_id) REFERENCES periodos (id),
  CONSTRAINT matriculas_promotoria_id_foreign FOREIGN KEY (promotoria_id) REFERENCES promotorias (id),
  CONSTRAINT ranura_valida CHECK (ranura BETWEEN 1 AND 6),
  CONSTRAINT estado_valido CHECK (estado IN ('pendiente', 'activa', 'cancelacion_solicitada', 'retirada'))
);
CREATE INDEX IF NOT EXISTS matriculas_periodo_id_foreign ON matriculas (periodo_id);
CREATE INDEX IF NOT EXISTS matriculas_promotoria_id_periodo_id_estado_index ON matriculas (promotoria_id, periodo_id, estado);
CREATE INDEX IF NOT EXISTS matriculas_institucion_periodo_estado ON matriculas (institucion_id, periodo_id, estado);

-- El cupo de promotoria. Era el trigger de MariaDB con `SIGNAL SQLSTATE
-- '45000'`: se conserva el MISMO estado y el mismo mensaje, que es lo que
-- reconoce `ErrorDeBaseDeDatos::esCupoAgotado()`.
--
-- El `FOR UPDATE` sobre la fila del cupo pone en fila a dos inscripciones que
-- compiten por el ultimo sitio; en READ COMMITTED cada consulta de la funcion
-- toma su propia foto, asi que el COUNT de despues de la espera ya ve la
-- matricula de la otra.
CREATE OR REPLACE FUNCTION cupo_promotoria_disponible() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_maximo      bigint;
  v_ocupados    bigint;
  v_promotoria  varchar(60);
  v_periodo     varchar(20);
BEGIN
  -- Una matricula retirada no ocupa sitio: nada que comprobar.
  IF NEW.estado = 'retirada' THEN
    RETURN NEW;
  END IF;

  -- Seguir ocupando el mismo sitio no pide uno nuevo.
  IF TG_OP = 'UPDATE' THEN
    IF OLD.estado <> 'retirada'
       AND OLD.promotoria_id = NEW.promotoria_id
       AND OLD.periodo_id = NEW.periodo_id THEN
      RETURN NEW;
    END IF;
  END IF;

  SELECT cupo_maximo INTO v_maximo
    FROM cupos_promotoria
   WHERE promotoria_id = NEW.promotoria_id
     AND periodo_id = NEW.periodo_id
     FOR UPDATE;

  -- Sin cupo definido para ese periodo, no hay tope.
  IF v_maximo IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT COUNT(*) INTO v_ocupados
    FROM matriculas
   WHERE promotoria_id = NEW.promotoria_id
     AND periodo_id = NEW.periodo_id
     AND estado <> 'retirada'
     AND (TG_OP = 'INSERT' OR id IS DISTINCT FROM NEW.id);

  IF v_ocupados >= v_maximo THEN
    SELECT nombre INTO v_promotoria FROM promotorias WHERE id = NEW.promotoria_id;
    SELECT nombre INTO v_periodo FROM periodos WHERE id = NEW.periodo_id;
    RAISE EXCEPTION USING
      ERRCODE = '45000',
      MESSAGE = v_promotoria || ' no tiene cupos disponibles para ' || v_periodo || ': '
                || v_ocupados || ' de ' || v_maximo
                || ' ocupados, contando las solicitudes pendientes.';
  END IF;

  RETURN NEW;
END
$$;

CREATE OR REPLACE TRIGGER cupo_promotoria_disponible_insert
  BEFORE INSERT ON matriculas
  FOR EACH ROW EXECUTE FUNCTION cupo_promotoria_disponible();

CREATE OR REPLACE TRIGGER cupo_promotoria_disponible_update
  BEFORE UPDATE ON matriculas
  FOR EACH ROW EXECUTE FUNCTION cupo_promotoria_disponible();

CREATE TABLE IF NOT EXISTS asignaciones_grupo (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  matricula_id    bigint NOT NULL,
  grupo_id        bigint NOT NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT una_vez_por_grupo UNIQUE (matricula_id, grupo_id),
  CONSTRAINT asignaciones_grupo_grupo_id_foreign FOREIGN KEY (grupo_id) REFERENCES grupos (id),
  CONSTRAINT asignaciones_grupo_matricula_id_foreign FOREIGN KEY (matricula_id) REFERENCES matriculas (id) ON DELETE CASCADE,
  CONSTRAINT fk_asignaciones_grupo_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id)
);
CREATE INDEX IF NOT EXISTS asignaciones_grupo_grupo_id_index ON asignaciones_grupo (grupo_id);
CREATE INDEX IF NOT EXISTS fk_asignaciones_grupo_institucion ON asignaciones_grupo (institucion_id);

CREATE TABLE IF NOT EXISTS sesiones_grupo (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  grupo_id        bigint NOT NULL,
  dia             smallint NOT NULL,
  hora_inicio     time(0) NOT NULL,
  hora_fin        time(0) NOT NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT una_sesion_por_dia_y_grupo UNIQUE (grupo_id, dia),
  CONSTRAINT fk_sesiones_grupo_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT sesiones_grupo_grupo_id_foreign FOREIGN KEY (grupo_id) REFERENCES grupos (id) ON DELETE CASCADE,
  CONSTRAINT dia_valido CHECK (dia BETWEEN 1 AND 6),
  CONSTRAINT hora_fin_posterior CHECK (hora_fin > hora_inicio)
);
CREATE INDEX IF NOT EXISTS sesiones_grupo_dia_hora_inicio_index ON sesiones_grupo (dia, hora_inicio);
CREATE INDEX IF NOT EXISTS fk_sesiones_grupo_institucion ON sesiones_grupo (institucion_id);

-- ----------------------------------------------------------------------------
-- Clases y asistencia
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS clases (
  id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id             bigint NOT NULL,
  grupo_id                   bigint NOT NULL,
  periodo_id                 bigint NOT NULL,
  fecha_hora                 timestamp(0) NOT NULL,
  registrada_por_id          bigint NULL,
  confirmaciones_requeridas  smallint NOT NULL DEFAULT 3,
  created_at                 timestamp(0) NULL,
  updated_at                 timestamp(0) NULL,
  CONSTRAINT clases_grupo_id_foreign FOREIGN KEY (grupo_id) REFERENCES grupos (id) ON DELETE CASCADE,
  CONSTRAINT clases_periodo_id_foreign FOREIGN KEY (periodo_id) REFERENCES periodos (id),
  CONSTRAINT clases_registrada_por_id_foreign FOREIGN KEY (registrada_por_id) REFERENCES perfiles (id) ON DELETE SET NULL,
  CONSTRAINT fk_clases_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT confirmaciones_requeridas_en_rango CHECK (confirmaciones_requeridas BETWEEN 0 AND 255)
);
CREATE INDEX IF NOT EXISTS clases_periodo_id_foreign ON clases (periodo_id);
CREATE INDEX IF NOT EXISTS clases_grupo_id_periodo_id_fecha_hora_index ON clases (grupo_id, periodo_id, fecha_hora);
CREATE INDEX IF NOT EXISTS clases_registrada_por_id_periodo_id_index ON clases (registrada_por_id, periodo_id);
CREATE INDEX IF NOT EXISTS clases_institucion_periodo_fecha ON clases (institucion_id, periodo_id, fecha_hora);

CREATE TABLE IF NOT EXISTS asistencias (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  clase_id        bigint NOT NULL,
  matricula_id    bigint NOT NULL,
  estado          varchar(10) COLLATE insensible NOT NULL,
  fecha_registro  timestamp(0) NOT NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT una_asistencia_por_clase_y_matricula UNIQUE (clase_id, matricula_id),
  CONSTRAINT asistencias_clase_id_foreign FOREIGN KEY (clase_id) REFERENCES clases (id) ON DELETE CASCADE,
  CONSTRAINT asistencias_matricula_id_foreign FOREIGN KEY (matricula_id) REFERENCES matriculas (id) ON DELETE CASCADE,
  CONSTRAINT fk_asistencias_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT estado_asistencia_valido CHECK (estado IN ('asistio', 'falto', 'excusa'))
);
CREATE INDEX IF NOT EXISTS asistencias_matricula_id_foreign ON asistencias (matricula_id);
CREATE INDEX IF NOT EXISTS fk_asistencias_institucion ON asistencias (institucion_id);

CREATE TABLE IF NOT EXISTS confirmaciones_clase (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  clase_id        bigint NOT NULL,
  matricula_id    bigint NOT NULL,
  fecha           timestamp(0) NOT NULL,
  origen          varchar(12) COLLATE insensible NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT una_confirmacion_por_clase_y_estudiante UNIQUE (clase_id, matricula_id),
  CONSTRAINT confirmaciones_clase_clase_id_foreign FOREIGN KEY (clase_id) REFERENCES clases (id) ON DELETE CASCADE,
  CONSTRAINT confirmaciones_clase_matricula_id_foreign FOREIGN KEY (matricula_id) REFERENCES matriculas (id) ON DELETE CASCADE,
  CONSTRAINT fk_confirmaciones_clase_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id)
);
CREATE INDEX IF NOT EXISTS confirmaciones_clase_matricula_id_foreign ON confirmaciones_clase (matricula_id);
CREATE INDEX IF NOT EXISTS fk_confirmaciones_clase_institucion ON confirmaciones_clase (institucion_id);

CREATE TABLE IF NOT EXISTS omisiones_archivadas (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id    bigint NOT NULL,
  grupo_id          bigint NOT NULL,
  fecha             date NOT NULL,
  archivada_por_id  bigint NULL,
  created_at        timestamp(0) NULL,
  updated_at        timestamp(0) NULL,
  CONSTRAINT omision_unica_por_grupo_y_fecha UNIQUE (grupo_id, fecha),
  CONSTRAINT fk_omisiones_archivadas_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT omisiones_archivadas_archivada_por_id_foreign FOREIGN KEY (archivada_por_id) REFERENCES perfiles (id) ON DELETE SET NULL,
  CONSTRAINT omisiones_archivadas_grupo_id_foreign FOREIGN KEY (grupo_id) REFERENCES grupos (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS omisiones_archivadas_archivada_por_id_foreign ON omisiones_archivadas (archivada_por_id);
CREATE INDEX IF NOT EXISTS fk_omisiones_archivadas_institucion ON omisiones_archivadas (institucion_id);

-- ----------------------------------------------------------------------------
-- Actividades: cursos, talleres, proyeccion y programas externos
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS instituciones_externas (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  nombre          varchar(120) COLLATE insensible NOT NULL,
  direccion       varchar(160) COLLATE insensible NULL,
  telefono        varchar(40) COLLATE insensible NULL,
  perfil_id       bigint NOT NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT instituciones_externas_perfil_id_unique UNIQUE (perfil_id),
  CONSTRAINT fk_instituciones_externas_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT instituciones_externas_perfil_id_foreign FOREIGN KEY (perfil_id) REFERENCES perfiles (id),
  CONSTRAINT nombre_de_institucion_externa_no_vacio CHECK (nombre <> '')
);
CREATE INDEX IF NOT EXISTS fk_instituciones_externas_institucion ON instituciones_externas (institucion_id);

CREATE TABLE IF NOT EXISTS actividades (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id          bigint NOT NULL,
  tipo                    varchar(20) COLLATE insensible NOT NULL,
  nombre                  varchar(80) COLLATE insensible NOT NULL,
  responsable_id          bigint NOT NULL,
  periodo_id              bigint NULL,
  institucion_externa_id  bigint NULL,
  cupo_maximo             integer NULL,
  token                   char(32) COLLATE insensible NOT NULL,
  abierta                 boolean NOT NULL DEFAULT true,
  created_at              timestamp(0) NULL,
  updated_at              timestamp(0) NULL,
  CONSTRAINT un_enlace_por_actividad UNIQUE (token),
  CONSTRAINT actividades_institucion_externa_id_foreign FOREIGN KEY (institucion_externa_id) REFERENCES instituciones_externas (id),
  CONSTRAINT actividades_periodo_id_foreign FOREIGN KEY (periodo_id) REFERENCES periodos (id),
  CONSTRAINT actividades_responsable_id_foreign FOREIGN KEY (responsable_id) REFERENCES perfiles (id),
  CONSTRAINT fk_actividades_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT nombre_de_actividad_no_vacio CHECK (nombre <> ''),
  CONSTRAINT cupo_de_actividad_positivo CHECK (cupo_maximo IS NULL OR cupo_maximo > 0),
  CONSTRAINT cupo_de_actividad_en_rango CHECK (cupo_maximo IS NULL OR cupo_maximo <= 65535),
  CONSTRAINT tipo_de_actividad_valido CHECK (tipo IN ('curso', 'taller', 'proyeccion', 'externo')),
  CONSTRAINT institucion_solo_en_programa_externo CHECK ((tipo = 'externo') = (institucion_externa_id IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS actividades_responsable_id_foreign ON actividades (responsable_id);
CREATE INDEX IF NOT EXISTS actividades_periodo_id_foreign ON actividades (periodo_id);
CREATE INDEX IF NOT EXISTS actividades_por_tipo_y_nombre ON actividades (tipo, nombre);
CREATE INDEX IF NOT EXISTS actividades_institucion_externa_id_foreign ON actividades (institucion_externa_id);
CREATE INDEX IF NOT EXISTS actividades_institucion_tipo_nombre ON actividades (institucion_id, tipo, nombre);

CREATE TABLE IF NOT EXISTS sesiones_actividad (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id       bigint NOT NULL,
  actividad_id         bigint NOT NULL,
  fecha                date NOT NULL,
  iniciada_en          timestamp(0) NULL,
  iniciada_por_id      bigint NULL,
  verificada_en        timestamp(0) NULL,
  verificada_por_id    bigint NULL,
  verificacion_origen  varchar(10) COLLATE insensible NULL,
  created_at           timestamp(0) NULL,
  updated_at           timestamp(0) NULL,
  CONSTRAINT un_encuentro_por_dia UNIQUE (actividad_id, fecha),
  CONSTRAINT fk_sesiones_actividad_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT sesiones_actividad_actividad_id_foreign FOREIGN KEY (actividad_id) REFERENCES actividades (id) ON DELETE CASCADE,
  CONSTRAINT sesiones_actividad_iniciada_por_id_foreign FOREIGN KEY (iniciada_por_id) REFERENCES perfiles (id) ON DELETE SET NULL,
  CONSTRAINT sesiones_actividad_verificada_por_id_foreign FOREIGN KEY (verificada_por_id) REFERENCES perfiles (id) ON DELETE SET NULL,
  CONSTRAINT origen_de_verificacion_valido CHECK (verificacion_origen IS NULL OR verificacion_origen IN ('propia', 'qr')),
  CONSTRAINT verificacion_completa_o_ninguna CHECK ((verificada_en IS NULL) = (verificacion_origen IS NULL))
);
CREATE INDEX IF NOT EXISTS sesiones_actividad_iniciada_por_id_foreign ON sesiones_actividad (iniciada_por_id);
CREATE INDEX IF NOT EXISTS sesiones_actividad_verificada_por_id_foreign ON sesiones_actividad (verificada_por_id);
CREATE INDEX IF NOT EXISTS sesiones_por_verificar ON sesiones_actividad (actividad_id, verificada_en);
CREATE INDEX IF NOT EXISTS fk_sesiones_actividad_institucion ON sesiones_actividad (institucion_id);

CREATE TABLE IF NOT EXISTS inscritos_actividad (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id    bigint NOT NULL,
  actividad_id      bigint NOT NULL,
  nombre_completo   varchar(90) COLLATE insensible NOT NULL,
  documento         varchar(15) COLLATE insensible NULL,
  telefono          varchar(15) COLLATE insensible NULL,
  correo            varchar(120) COLLATE insensible NULL,
  fecha_nacimiento  date NULL,
  edad              smallint NULL,
  perfil_id         bigint NULL,
  origen            varchar(12) COLLATE insensible NOT NULL,
  created_at        timestamp(0) NULL,
  updated_at        timestamp(0) NULL,
  CONSTRAINT una_inscripcion_por_documento UNIQUE (actividad_id, documento),
  CONSTRAINT fk_inscritos_actividad_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT inscritos_actividad_actividad_id_foreign FOREIGN KEY (actividad_id) REFERENCES actividades (id) ON DELETE CASCADE,
  CONSTRAINT inscritos_actividad_perfil_id_foreign FOREIGN KEY (perfil_id) REFERENCES perfiles (id) ON DELETE SET NULL,
  CONSTRAINT nombre_de_inscrito_no_vacio CHECK (nombre_completo <> ''),
  CONSTRAINT edad_de_inscrito_creible CHECK (edad IS NULL OR (edad > 0 AND edad < 120)),
  CONSTRAINT origen_de_inscrito_valido CHECK (origen IN ('enlace', 'en_sesion', 'lista'))
);
CREATE INDEX IF NOT EXISTS inscritos_actividad_perfil_id_foreign ON inscritos_actividad (perfil_id);
CREATE INDEX IF NOT EXISTS inscritos_por_actividad_y_nombre ON inscritos_actividad (actividad_id, nombre_completo, id);
CREATE INDEX IF NOT EXISTS fk_inscritos_actividad_institucion ON inscritos_actividad (institucion_id);

CREATE TABLE IF NOT EXISTS asistencias_actividad (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  sesion_id       bigint NOT NULL,
  inscrito_id     bigint NOT NULL,
  estado          varchar(12) COLLATE insensible NOT NULL,
  fecha_registro  timestamp(0) NOT NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT una_marca_por_sesion UNIQUE (sesion_id, inscrito_id),
  CONSTRAINT asistencias_actividad_inscrito_id_foreign FOREIGN KEY (inscrito_id) REFERENCES inscritos_actividad (id) ON DELETE CASCADE,
  CONSTRAINT asistencias_actividad_sesion_id_foreign FOREIGN KEY (sesion_id) REFERENCES sesiones_actividad (id) ON DELETE CASCADE,
  CONSTRAINT fk_asistencias_actividad_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT estado_de_asistencia_actividad_valido CHECK (estado IN ('asistio', 'falto', 'excusa'))
);
CREATE INDEX IF NOT EXISTS asistencias_actividad_inscrito_id_foreign ON asistencias_actividad (inscrito_id);
CREATE INDEX IF NOT EXISTS fk_asistencias_actividad_institucion ON asistencias_actividad (institucion_id);

-- ----------------------------------------------------------------------------
-- Las del framework: sesion, cache, colas
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sessions (
  id             varchar(255) COLLATE insensible NOT NULL PRIMARY KEY,
  user_id        bigint NULL,
  ip_address     varchar(45) COLLATE insensible NULL,
  user_agent     text COLLATE insensible NULL,
  payload        text COLLATE insensible NOT NULL,
  last_activity  integer NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_user_id_index ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_last_activity_index ON sessions (last_activity);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  email       varchar(255) COLLATE insensible NOT NULL PRIMARY KEY,
  token       varchar(255) COLLATE insensible NOT NULL,
  created_at  timestamp(0) NULL
);

CREATE TABLE IF NOT EXISTS cache (
  key         varchar(255) COLLATE insensible NOT NULL PRIMARY KEY,
  value       text COLLATE insensible NOT NULL,
  expiration  integer NOT NULL
);
CREATE INDEX IF NOT EXISTS cache_expiration_index ON cache (expiration);

CREATE TABLE IF NOT EXISTS cache_locks (
  key         varchar(255) COLLATE insensible NOT NULL PRIMARY KEY,
  owner       varchar(255) COLLATE insensible NOT NULL,
  expiration  integer NOT NULL
);
CREATE INDEX IF NOT EXISTS cache_locks_expiration_index ON cache_locks (expiration);

CREATE TABLE IF NOT EXISTS jobs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue         varchar(255) COLLATE insensible NOT NULL,
  payload       text COLLATE insensible NOT NULL,
  attempts      smallint NOT NULL,
  reserved_at   bigint NULL,
  available_at  bigint NOT NULL,
  created_at    bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS jobs_queue_index ON jobs (queue);

CREATE TABLE IF NOT EXISTS job_batches (
  id              varchar(255) COLLATE insensible NOT NULL PRIMARY KEY,
  name            varchar(255) COLLATE insensible NOT NULL,
  total_jobs      integer NOT NULL,
  pending_jobs    integer NOT NULL,
  failed_jobs     integer NOT NULL,
  failed_job_ids  text COLLATE insensible NOT NULL,
  options         text COLLATE insensible NULL,
  cancelled_at    integer NULL,
  created_at      integer NOT NULL,
  finished_at     integer NULL
);

CREATE TABLE IF NOT EXISTS failed_jobs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid        varchar(255) COLLATE insensible NOT NULL,
  connection  text COLLATE insensible NOT NULL,
  queue       text COLLATE insensible NOT NULL,
  payload     text COLLATE insensible NOT NULL,
  exception   text COLLATE insensible NOT NULL,
  failed_at   timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
  CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid)
);
