-- ============================================================================
-- 04 · El panel de todas las instituciones
-- ============================================================================
--
-- Paso 4b de la version multi-institucion. El panel vive en su propio host
-- (`panel.<dominio base>`) y lo usan los OPERADORES: quien presta el servicio,
-- no una institucion. Decision del usuario (02/10/2026): son una tabla aparte y
-- no un rol dentro de la institucion 1, para que un administrador de una casa
-- no pueda ascender nunca a operador de todas.
--
-- 1. `operadores`, SIN `institucion_id` y por eso sin RLS: no son de ninguna.
--    Se crean por consola (`php artisan operador:crear`), nunca desde una
--    pantalla.
-- 2. Los subdominios `panel` y `www` quedan reservados: el primero es el del
--    panel, y el segundo es el que se escribe por costumbre delante del dominio
--    base.
--
-- Lo corre el DUEÑO de las tablas (`php artisan migrate --database=pgsql_dueno`).
-- Los permisos de la aplicacion sobre la tabla nueva los da el
-- `ALTER DEFAULT PRIVILEGES` de 02-rls.sql. Idempotente.
-- ============================================================================

CREATE TABLE IF NOT EXISTS operadores (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario         varchar(150) COLLATE insensible NOT NULL,
  nombre          varchar(90) COLLATE insensible NOT NULL,
  password        varchar(255) COLLATE insensible NOT NULL,
  activo          boolean NOT NULL DEFAULT true,
  remember_token  varchar(100) COLLATE insensible NULL,
  ultimo_acceso   timestamp(0) NULL,
  created_at      timestamp(0) NULL,
  updated_at      timestamp(0) NULL,
  CONSTRAINT operadores_usuario_unique UNIQUE (usuario),
  CONSTRAINT usuario_de_operador_no_vacio CHECK (usuario <> ''),
  CONSTRAINT nombre_de_operador_no_vacio CHECK (nombre <> '')
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'subdominio_no_reservado') THEN
    ALTER TABLE instituciones ADD CONSTRAINT subdominio_no_reservado
      CHECK (subdominio NOT IN ('panel', 'www'));
  END IF;
END
$$;
