-- ============================================================================
-- 05 · Entrar a una institucion desde el panel (suplantacion)
-- ============================================================================
--
-- Paso 4c de la version multi-institucion. Un operador del panel entra a una
-- institucion como uno de sus ADMINISTRADORES (decision del usuario,
-- 02/10/2026). El panel y la institucion viven en hosts distintos, y una cookie
-- es de su host: el panel no puede abrir una sesion en el otro. Por eso el
-- panel deja aqui un TOKEN de un solo uso y manda al navegador al dominio de la
-- institucion, que lo canjea.
--
-- - El token se guarda en SHA-256 (64 caracteres del generador seguro, como el
--   de «olvide mi contraseña»): el enlace viaja por la barra de direcciones y
--   no puede servir dos veces ni pasados 60 segundos.
-- - La fila lleva `institucion_id` y RLS como cualquier dato: el token solo se
--   encuentra en el dominio de SU institucion. Canjearlo en otro es no
--   encontrarlo.
-- - Las filas se QUEDAN: son el registro de quien entro, como quien y cuando.
--
-- Lo corre el DUEÑO de las tablas. Idempotente.
-- ============================================================================

CREATE TABLE IF NOT EXISTS suplantaciones (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id  bigint NOT NULL,
  operador_id     bigint NOT NULL,
  user_id         bigint NOT NULL,
  token           char(64) COLLATE insensible NOT NULL,
  created_at      timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
  usado_en        timestamp(0) NULL,
  CONSTRAINT suplantaciones_token_unique UNIQUE (token),
  CONSTRAINT fk_suplantaciones_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT fk_suplantaciones_operador FOREIGN KEY (operador_id) REFERENCES operadores (id) ON DELETE CASCADE,
  CONSTRAINT fk_suplantaciones_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS fk_suplantaciones_institucion ON suplantaciones (institucion_id);
CREATE INDEX IF NOT EXISTS fk_suplantaciones_operador ON suplantaciones (operador_id);
CREATE INDEX IF NOT EXISTS fk_suplantaciones_user ON suplantaciones (user_id);

ALTER TABLE suplantaciones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS por_institucion ON suplantaciones;
CREATE POLICY por_institucion ON suplantaciones
  USING (institucion_id = institucion_de_la_sesion())
  WITH CHECK (institucion_id = institucion_de_la_sesion());
