-- ============================================================================
-- 08 · La alerta semanal de los programas externos
-- ============================================================================
--
-- Traido de `main` (03/10/2026, pedido del usuario). Una semana de lunes a
-- domingo sin ninguna clase iniciada alla sale en Alertas, solo para
-- administracion. Se calcula al abrir; aqui se guarda lo que la gobierna y lo
-- que alguien decidio sobre ella.
--
-- - `instituciones_externas.clases_desde` / `clases_hasta`: entre que fechas se
--   dicta alla. Sin inicio no se avisa; sin fin se avisa hasta que se ponga.
-- - `omisiones_externas`: la causa de una semana sin clase (las tres de los
--   grupos), guardada por el LUNES de la semana. Lleva `institucion_id` y RLS
--   como cualquier dato.
--
-- Lo corre el DUEÑO de las tablas. Idempotente.
-- ============================================================================

ALTER TABLE instituciones_externas ADD COLUMN IF NOT EXISTS clases_desde date NULL;
ALTER TABLE instituciones_externas ADD COLUMN IF NOT EXISTS clases_hasta date NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'clases_externas_en_orden') THEN
    ALTER TABLE instituciones_externas ADD CONSTRAINT clases_externas_en_orden
      CHECK (clases_hasta IS NULL OR clases_desde IS NULL OR clases_hasta >= clases_desde);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS omisiones_externas (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id      bigint NOT NULL,
  actividad_id        bigint NOT NULL,
  semana              date NOT NULL,
  causa               varchar(12) COLLATE insensible NOT NULL,
  clasificada_por_id  bigint NULL,
  created_at          timestamp(0) NULL,
  updated_at          timestamp(0) NULL,
  CONSTRAINT omision_externa_unica_por_semana UNIQUE (actividad_id, semana),
  CONSTRAINT fk_omisiones_externas_institucion FOREIGN KEY (institucion_id) REFERENCES instituciones (id),
  CONSTRAINT omisiones_externas_actividad_id_foreign FOREIGN KEY (actividad_id) REFERENCES actividades (id) ON DELETE CASCADE,
  CONSTRAINT omisiones_externas_clasificada_por_id_foreign FOREIGN KEY (clasificada_por_id) REFERENCES perfiles (id) ON DELETE SET NULL,
  CONSTRAINT causa_de_omision_externa_valida CHECK (causa IN ('excusa', 'falta', 'institucion'))
);
CREATE INDEX IF NOT EXISTS fk_omisiones_externas_institucion ON omisiones_externas (institucion_id);
CREATE INDEX IF NOT EXISTS omisiones_externas_clasificada_por_id_foreign ON omisiones_externas (clasificada_por_id);

ALTER TABLE omisiones_externas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS por_institucion ON omisiones_externas;
CREATE POLICY por_institucion ON omisiones_externas
  USING (institucion_id = institucion_de_la_sesion())
  WITH CHECK (institucion_id = institucion_de_la_sesion());
